server:
  port: 8082
spring:
  application:
    name: AdoptApp-Backend

  datasource:
    url: jdbc:postgresql://32.194.142.199:5432/adoptapp_db
    username: postgres
    password: bOAr3TE86lNIKFuavSVQDe49mFxj2OySzy
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://ms-auth-service-container:8080/.well-known/jwks.json
    uri: https://adoptapp.site
  uri-front: "https://adoptapp.site"
api:
  auth:
    uri: "https://auth.adoptapp.site"

